name: webview_windows_example
description: Demonstrates how to use the webview_windows plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_windows:
    path: ../
  window_manager: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
